name: Build and test eshop

on:
  workflow_dispatch:
  push:

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN}}


      - name: Setupp NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10
      
      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with: 
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
          restore-keys: node_modules-

      - name: Install packages with npm
        run: |
          npm ci
  
  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN}}


      - name: Setupp NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10
      
      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with: 
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors
      - name: Cache node modules and build folder
        if: ${{ github.ref == 'refs/heads/master'}}
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restory-keys: ${{ runner.os }}-build-${{ github.run_id }}
  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN}}


      - name: Setupp NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10
      
      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with: 
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      - name: Run tests
        run: |
          npm rebuild node-sass --force
          npm run test -- --colors

  Deploy:
    needs: [Build, Test]
    if: ${{ github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest

    steps: 
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN}}
      - name: Load Node modules and build folder
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os }}-build-${{ github.run_id }}
      - name: Deploy to firebase
        uses: lowply/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: vevj00